#!/bin/bash

# Generate AUTHORS file automatically from git contributors

{
    echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT."
    echo "# This file lists all contributors to the repository."
    echo "# See hack/generate-authors.sh to make modifications."
    echo

    git log --format='%aN <%aE>' | sort -fu
} > AUTHORS
