#!/usr/bin/env bash
set -e

# Change to the repository root directory safely
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."

# Stream the header and the git history directly into the AUTHORS file
{
    echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT."
    echo "# This file lists all contributors to the repository."
    echo "# See hack/generate-authors.sh to make modifications."
    echo ""
    git log --format='%aN <%aE>' | sort -fu
} > AUTHORS
